# version: "3"

# services:
#   kafka:
#     image: 'bitnami/kafka:3.6.1'
#     ports:
#       - "9092:9092"
#       - "9094:9094"
#     volumes:
#       - "kafka_data:/bitnami"
#     environment:
#       # Settings for KRaft
#       - KAFKA_CFG_NODE_ID=0
#       - KAFKA_CFG_PROCESS_ROLES=controller,broker
#       - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
#       # Listeners
#       - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
#       - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
#       - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
#       - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#       # Message size
#       - KAFKA_CFG_MESSAGE_MAX_BYTES=20971520

#   backend:
#     build:
#       context: .
#       dockerfile: backend/Dockerfile
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./backend:/app/backend
#     depends_on:
#       - kafka

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: front/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./front:/app/front
  #   depends_on:
  #     - backend

# volumes:
#   kafka_data:
#     driver: local



version: "2"

services:
  kafka:
    image: 'bitnami/kafka:3.6.1'
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # Settings for KRaft
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Message size and memory heap settings
      - KAFKA_CFG_MESSAGE_MAX_BYTES=209715200
      - KAFKA_HEAP_OPTS=-Xmx2048m -Xms1024m

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - kafka
  
  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app/front

volumes:
  kafka_data:
    driver: local